apiVersion: v1
kind: Service

metadata:
  name: pedidos-service

spec:
  selector:
    app: pedidos

  ports:
  - port: 80
    targetPort: 3001

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: pagamentos-service
spec:
  selector:
    app: pagamentos
  ports:
  - port: 80
    targetPort: 3002
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: estoque-service
spec:
  selector:
    app: estoque
  ports:
  - port: 80
    targetPort: 3003
  type: ClusterIP